// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rpapejqnvbxujurjfvjs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwYXBlanFudmJ4dWp1cmpmdmpzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwODk4MDgsImV4cCI6MjA2MzY2NTgwOH0.yRfu5x_K5gznMZZ1K7t7DvJsbCp3tV459Ey7O7lXHe4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);